### ISSUE TITLE
Define a zero pad

### ISSUE THREAD

**Issue by fire** [ScrimpyCat/Tonic#1]
How do I define a zero_pad given the first part is parsed and then the rest is assume to be zero padded to 1024?

**Comment by ScrimpyCat** [comment]
A pad of 1024 zero bytes? There's a few ways you could handle that depending on whether you want the data in your loaded result, want it to crash if the data is not 0, or just want to skip 1024 bytes.

### Padding inside

For the examples below just assume our data is: `<<1 :: size(8), 0 :: size(8192), 2 :: size(8)>>` (one byte = 1, followed by 1024 bytes = 0, followed by 1 byte = 2).

#### Read data including padding

If you simply want to read the data as one byte, followed by the 1024 byte section, followed by the last byte, you could do something like this:
```elixir
defmodule Example do
    use Tonic

    uint8()
    repeat 1024, :uint8
    uint8()
end
```

Which will return something like: `{{1, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...], 2}, <<>>}`

Alternatively you could also wrap the repeat in a chunk.
```elixir
defmodule Example do
    use Tonic

    uint8()
    chunk 1024 do
        repeat :uint8
    end
    uint8()
end
```

#### Read data, skip padding

If you don't want the padding to be included in your loaded data, you can wrap it in a skip block.
```elixir
defmodule Example do
    use Tonic

    uint8()
    skip do
        repeat 1024, :uint8
    end
    uint8()
end
```

Which will return: `{{1, 2}, <<>>}`

#### Read data including padding of zeroes

If you want to make sure the padding section consists of only 0 bytes (and crash/fail to load if it does not), you can utilise functions to check the result is what you expect.

```elixir
defmodule Example do
    use Tonic

    uint8()
    repeat :padding, 1024, fn { _, value } ->
        Enum.map(value, fn { i } -> i end) # Format result to match earlier examples
    end do
        uint8 :pad, fn { _, 0 } -> 0 end # Only match 0 bytes
    end
    uint8()
end
```

Alternatively you could create your own type that only matches against 0 bytes.
```elixir
defmodule Padding do
    use Tonic

    type :zero_pad, fn <<0 :: size(8), data :: binary>>, name, _ -> { { name, 0 }, data } end
end

defmodule Example do
    use Tonic
    import Padding

    uint8()
    repeat 1024, :zero_pad
    uint8()
end
```

### Padding at end

Now if the padding is at the end of the data (which I think is what your use case is), there's some additional ways it could also be handled. For these examples assume our data is: `<<1 :: size(8), 0 :: size(8192)>>`.

#### Read data excluding padding

The first is to either handle it or not handle it outside of the parser.
```elixir
defmodule Example do
    use Tonic

    uint8()
end
```

Will return: `{{1}, <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>}`

So you could either just ignore the padding, or could match against it there. e.g. `{ data, <<0 :: size(8192)>> } = Tonic.load(<<1 :: size(8), 0 :: size(8192)>>, Example)`

#### Read data including padding

If you want to handle it in the parser, you could either handle it like in the aforementioned examples by providing the length. However that will only guarantee there's at least the 1024 byte block, it doesn't guarantee there isn't any additional data following it. To enforce that, you could create some types.

```elixir
defmodule Padding do
    use Tonic

    type :zero_pad, fn <<0 :: size(8), data :: binary>>, name, _ -> { { name, 0 }, data } end
    type :eof!, fn <<>>, name, _ -> { { name, :eof }, <<>> } end
end

defmodule Example do
    use Tonic

    uint8()
    repeat 1024, :zero_pad
    eof!()
end
```

Will return: `{{1, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...], :eof}, <<>>}`

Or will crash if there is more data following it. Unfortunately it will add an additional value (`:eof`) to the returned dataset. While this could be removed, another way to handle it is with a type that checks for all the padding.
```elixir
defmodule Padding do
    use Tonic

    type :end_zero_pad, fn <<0 :: size(8192)>>, name, _ -> { { name, List.duplicate(0, 1024) }, <<>> } end
end

defmodule Example do
    use Tonic

    uint8()
    end_zero_pad()
end
```

Which will return: `{{1, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...]}, <<>>}`

Or another way would be to repeat till the end of the binary and check the result's length.
```elixir
defmodule Example do
    use Tonic

    uint8()
    repeat :padding, fn _ -> false end, fn { _, padding } when length(padding) == 1024 ->
        Enum.map(padding, fn { 0 } -> 0 end)
    end do
        uint8()
    end
end
```

On a side note, if asserting the parser has reached the end of the binary is commonly desired behaviour. It could be a good candidate for having its own function. So I think I might actually add something like an `empty!/0` function to assert it's at the end of the binary, if not raise some exception.

Also let me know if that didn't address your issue.

**Comment by fire** [comment]
The other tricky part I had is calculating the length. So the initial part could be a variant number of bytes (because the list of server changes), but the rest is padded to 1024 bytes with the bytes being a calculated number. The parser exits if the less than or equal 1024 bytes isn't zeroed. 

```
[client id] (uint64) // globally unique identifier for an authenticated client
[num server addresses] (uint32) // in [1,32]
<for each server address>
{
    [address type] (uint8) // value of 1 = IPv4 address, 2 = IPv6 address.
    <if IPV4 address>
    {
        // for a given IPv4 address: a.b.c.d:port
        [a] (uint8)
        [b] (uint8)
        [c] (uint8)
        [d] (uint8)
        [port] (uint16)
    }
    <else IPv6 address>
    {
        // for a given IPv6 address: [a:b:c:d:e:f:g:h]:port
        [a] (uint16)
        [b] (uint16)
        [c] (uint16)
        [d] (uint16)
        [e] (uint16)
        [f] (uint16)
        [g] (uint16)
        [h] (uint16)
        [port] (uint16)
    }
}
[client to server key] (32 bytes)
[server to client key] (32 bytes)
[user data] (256 bytes) // user defined data specific to this protocol id
<zero pad to 1024 bytes>
```

Before I posted here I took the ignore data if it is present approach.

https://github.com/networkprotocol/netcode.io/blob/master/STANDARD.md is the standard I'm trying to implement.

https://github.com/fire/netcode/blob/master/lib/netcode/ConnectToken.ex

https://github.com/fire/netcode/blob/master/lib/netcode/ConnectTokenData.ex

**Comment by fire** [comment]
"Unused bytes are zero padded."

So in that example the max number of bytes is 1024. The initial part is some bytes and the rest is set to 0. If they're not 0 crash.

**Comment by ScrimpyCat** [comment]
There's a few issues with how you're trying to use the library (unfortunately the docs for this project were not that great).

The first is using the `get/1` function for the __"for each server address"__ part. For the length field of the repeat function, a function isn't actually a valid argument (the get function is "special"). So trying to do `repeat :server_address, Netcode.ConnectTokenData.verify_num_servers(get(:num_server_addresses)) do end` will not work correctly, instead what you're actually after is `repeat :server_address, get(:num_server_addresses, &verify_num_servers/1) do end`. See [`get/2`](https://hexdocs.pm/tonic/Tonic.html#get/2) for more information.

The second is using the `length:` option with types. Types don't actually accept options like this, the only exception is the `string` type (however that works quite differently). So trying to do `uint8 :client_to_server_key, length: 32` won't do what you expect, instead what you want is `repeat :client_to_server_key, 32, :uint8`.

As for the padding, at least according to the spec it doesn't seem like it really matters if you parse it or not? If you don't need to parse it, your `Netcode.ConnectTokenData` module could simply be:

```elixir
defmodule Netcode.ConnectTokenData do
  use Tonic, optimize: true

  endian :little

  uint64 :client_id
  uint32 :num_server_addresses
  repeat :server_address, get(:num_server_addresses, &verify_num_servers/1) do
    uint8 :address_type
    on get(:address_type) do
      # value of 1 = IPv4 address, 2 = IPv6 address.
      1 ->
        # for a given IPv4 address: a.b.c.d:port
        uint8 :a
        uint8 :b
        uint8 :c
        uint8 :d
        uint16 :port
      2 ->
        # for a given IPv6 address: [a:b:c:d:e:f:g:h]:port
        uint16 :a
        uint16 :b
        uint16 :c
        uint16 :d
        uint16 :e
        uint16 :f
        uint16 :g
        uint16 :h
        uint16 :port
    end
  end
  repeat :client_to_server_key, 32, :uint8
  repeat :server_to_client_key, 32, :uint8
  repeat :user_data, 256, :uint8 # user defined data specific to this protocol id

  @doc """
  Verify number of servers is [1,32].
  """
  def verify_num_servers(num) do
    cond do
      num in 1..32 -> num
      true -> exit "Invalid number of servers."
    end
  end
end
```

This will load this example data like so:
```elixir
iex(1)> Tonic.load <<1 :: size(64)-little, 1 :: size(32)-little, 1, 10, 11, 12, 13, 256 :: size(16)-little, 1 :: size(256), 1 :: size(256), 1 :: size(2048), 0 :: size(5480)>>, Netcode.ConnectTokenData
{{{:client_id, 1}, {:num_server_addresses, 1},
  {:server_address,
   [{{:address_type, 1}, {:a, 10}, {:b, 11}, {:c, 12}, {:d, 13},
     {:port, 256}}]},
  {:client_to_server_key,
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 1]},
  {:server_to_client_key,
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 1]},
  {:user_data,
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...]}},
 <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>}
```

If you do however want to handle the padding, you can refer to some of the previous suggestions for possible ways you could handle that. Or I just added the `empty!/0` function mentioned previously (not currently available on hex but will publish shortly), which could let you enforce that data is in fact 1024 bytes by doing something like:

```elixir
defmodule Netcode.ConnectTokenData do
  use Tonic, optimize: true

  endian :little

  chunk 1024 do
    uint64 :client_id
    uint32 :num_server_addresses
    repeat :server_address, get(:num_server_addresses, &verify_num_servers/1) do
      uint8 :address_type
      on get(:address_type) do
        # value of 1 = IPv4 address, 2 = IPv6 address.
        1 ->
          # for a given IPv4 address: a.b.c.d:port
          uint8 :a
          uint8 :b
          uint8 :c
          uint8 :d
          uint16 :port
        2 ->
          # for a given IPv6 address: [a:b:c:d:e:f:g:h]:port
          uint16 :a
          uint16 :b
          uint16 :c
          uint16 :d
          uint16 :e
          uint16 :f
          uint16 :g
          uint16 :h
          uint16 :port
      end
    end
    repeat :client_to_server_key, 32, :uint8
    repeat :server_to_client_key, 32, :uint8
    repeat :user_data, 256, :uint8 # user defined data specific to this protocol id
  end
  empty!()

  @doc """
  Verify number of servers is [1,32].
  """
  def verify_num_servers(num) do
    cond do
      num in 1..32 -> num
      true -> exit "Invalid number of servers."
    end
  end
end
```

This will load this example data like so:
```elixir
iex(1)> Tonic.load <<1 :: size(64)-little, 1 :: size(32)-little, 1, 10, 11, 12, 13, 256 :: size(16)-little, 1 :: size(256), 1 :: size(256), 1 :: size(2048), 0 :: size(5480)>>, Netcode.ConnectTokenData
{{{:client_id, 1}, {:num_server_addresses, 1},
  {:server_address,
   [{{:address_type, 1}, {:a, 10}, {:b, 11}, {:c, 12}, {:d, 13},
     {:port, 256}}]},
  {:client_to_server_key,
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 1]},
  {:server_to_client_key,
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 1]},
  {:user_data,
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...]}}, <<>>}
```
